ALTER TABLE stock_master ADD COLUMN IF NOT EXISTS erp_en NUMERIC;
ALTER TABLE stock_master ADD COLUMN IF NOT EXISTS erp_boy NUMERIC;
ALTER TABLE stock_master ADD COLUMN IF NOT EXISTS erp_yukseklik NUMERIC;
ALTER TABLE stock_master ADD COLUMN IF NOT EXISTS erp_cap NUMERIC;
