ALTER TABLE stock_master ADD COLUMN IF NOT EXISTS specific_gravity NUMERIC;
ALTER TABLE stock_master ADD COLUMN IF NOT EXISTS cinsi TEXT;
ALTER TABLE stock_master ADD COLUMN IF NOT EXISTS alasim TEXT;
ALTER TABLE stock_master ADD COLUMN IF NOT EXISTS tamper TEXT;
