ALTER TABLE matched_offer_lines
  ADD COLUMN IF NOT EXISTS kg NUMERIC NULL,
  ADD COLUMN IF NOT EXISTS talas_mik NUMERIC NULL,
  ADD COLUMN IF NOT EXISTS musteri_no TEXT NULL,
  ADD COLUMN IF NOT EXISTS musteri_parca_no TEXT NULL;
